#!/usr/bin/env python
"""
Extract time delay surfaces from potential FITS files for each sample.

Computes Fermat potential-based time delays from lenstool potential maps
and outputs FITS files with time delay surfaces in days.

Time delay formula:
  tau = (1 + z_lens) * (D_l * D_s / (D_ls * c)) * (Fermat potential)
  
where Fermat potential = 0.5 * |theta - beta|^2 - psi(theta)

SOURCE.DAT COORDINATE INFERENCE
================================
This script supports inferring per-sample source plane coordinates from source.dat files
generated by lenstool. This enables higher accuracy time delay calculations where each
lens model uses its own inferred source position rather than a global fixed position.

How it works:
  1. source.dat files contain arcsecond OFFSETS from a reference position
  2. Reference coordinates are read from the corresponding PAR file (e.g., sample_00027_z1.524.par)
  3. Offsets are converted to absolute coordinates using: 
     abs_coord = ref_coord + offset_arcsec / 3600.0
  4. Multiple source positions (e.g., 1A, 1B, 1C) are combined via spherical mean
  5. The resulting source position is used for that sample's time delay calculation

Configuration requirements for source.dat inference:
  
  "source_plane_coords": "infer_from_source.dat"  <- Special value to enable inference
  
  "source_dat_directory": "output/poten/selected_output"  <- Directory containing .dat files
  
  "source_dat_object_id_mapping": {
    "A1": "1A",  <- Maps our image IDs to source.dat object IDs
    "A2": "1B",
    "A3": "1C"
  }
  
  "source_plane_coords_default": "11h53m19.6s +07d55m57s"  <- Fallback if source.dat unavailable

  File naming convention:
    - PAR file: sample_XXXXX_zZ.ZZZ.par (e.g., sample_00027_z1.524.par)
    - Source.dat: sample_XXXXX_zZ.ZZZ_source.dat (e.g., sample_00027_z1.524_source.dat)
  
  The PAR file is expected in "sample_input/" directory relative to execution directory.
  The source.dat file path is constructed from "source_dat_directory" config option.
"""

import os
import sys
import json
import argparse
import numpy as np
from pathlib import Path
from astropy.io import fits
from astropy.wcs import WCS
from astropy.coordinates import SkyCoord
import astropy.units as u
from astropy.constants import c
import warnings

# Add parent directory to path for importing coord_utils
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from single_model.coord_utils import parse_coordinate_string


def load_config(config_path):
    """Load configuration from JSON file."""
    with open(config_path, 'r') as f:
        return json.load(f)


def get_reference_coordinates(par_file_path):
    """
    Extract reference coordinates from PAR file.
    
    The reference coordinates are used as the origin for interpreting arcsecond offsets
    in source.dat files. These appear on the "reference" line in the PAR file:
    
      reference     3 178.330251 7.932518
      
    where 178.330251 is RA (degrees) and 7.932518 is Dec (degrees).
    
    Args:
        par_file_path: Path to the .par file (e.g., sample_00027_z1.524.par)
        
    Returns:
        Tuple of (ra_deg, dec_deg) or (None, None) if not found
    """
    try:
        with open(par_file_path, 'r') as f:
            for line in f:
                if line.strip().startswith('reference'):
                    parts = line.strip().split()
                    if len(parts) >= 4:
                        ra_deg = float(parts[2])
                        dec_deg = float(parts[3])
                        return ra_deg, dec_deg
    except Exception as e:
        print(f"    WARNING: Failed to read reference coordinates from PAR file: {e}")
    
    return None, None


def read_source_dat_coordinates(source_dat_path, par_file_path, object_ids, id_mapping=None):
    """
    Read source coordinates from source.dat file and convert to absolute coordinates.
    
    The source.dat file format contains arcsecond OFFSETS from a reference position:
      object_id  delta_ra_arcsec  delta_dec_arcsec  [other_columns...]
      
    Example source.dat content:
      1A  -2.34  +1.89  ...
      1B  -1.45  +2.10  ...
      1C  -3.01  +1.67  ...
    
    These offsets are relative to reference coordinates stored in the PAR file.
    
    IMPORTANT: lenstool coordinate convention:
      - +RA arcsec is WEST direction (opposite to increasing RA)
      - +Dec arcsec is NORTH direction (same as increasing Dec)
    
    Absolute coordinates are computed as:
      abs_ra_deg = ref_ra_deg - delta_ra_arcsec / 3600.0  (note: subtract RA)
      abs_dec_deg = ref_dec_deg + delta_dec_arcsec / 3600.0
    
    Args:
        source_dat_path: Path to source.dat file (e.g., output/poten/selected_output/sample_00027_z1.524_source.dat)
        par_file_path: Path to corresponding PAR file with reference coordinates
        object_ids: List of object IDs to extract (e.g., ["A1", "A2", "A3"])
        id_mapping: Dict mapping our object IDs to source.dat object IDs
                   (e.g., {"A1": "1A", "A2": "1B", "A3": "1C"})
        
    Returns:
        List of coordinate strings in "RA_deg Dec_deg" format, or None if not found
        
    Example:
        >>> coords = read_source_dat_coordinates(
        ...     "sample_00027_z1.524_source.dat",
        ...     "sample_input/sample_00027_z1.524.par",
        ...     ["A1", "A2", "A3"],
        ...     {"A1": "1A", "A2": "1B", "A3": "1C"}
        ... )
        >>> coords
        ['178.3284 7.9321', '178.3292 7.9298', '178.3301 7.9284']
    """
    if id_mapping is None:
        id_mapping = {oid: oid for oid in object_ids}
    
    # Get reference coordinates from PAR file
    ref_ra_deg, ref_dec_deg = get_reference_coordinates(par_file_path)
    if ref_ra_deg is None or ref_dec_deg is None:
        print(f"    WARNING: Could not read reference coordinates from {par_file_path}")
        return None
    
    print(f"    Reference coordinates (from {Path(par_file_path).name}): RA={ref_ra_deg:.6f}°, Dec={ref_dec_deg:.6f}°")
    
    try:
        coords = []
        with open(source_dat_path, 'r') as f:
            lines = f.readlines()
        
        # Parse source.dat file (format: object_id, delta_ra_arcsec, delta_dec_arcsec, ...)
        for obj_id in object_ids:
            source_id = id_mapping.get(obj_id, obj_id)
            found = False
            
            for line in lines:
                parts = line.strip().split()
                if not parts or parts[0].startswith('#'):
                    continue
                # First column is object ID
                if parts[0] == source_id:
                    # Second and third columns are RA and Dec offsets in arcseconds
                    # NOTE: lenstool convention: +RA arcsec is WEST (opposite RA direction)
                    # and +Dec arcsec is NORTH (same Dec direction)
                    try:
                        delta_ra_arcsec = float(parts[1])
                        delta_dec_arcsec = float(parts[2])
                        
                        # Print the source.dat line for this object
                        print(f"      {obj_id:2s} ({source_id:2s}): {line.strip()}")
                        
                        # Convert arcseconds to degrees
                        # RA: flip sign because +arcsec is WEST (negative RA direction)
                        # Dec: keep sign as is (+arcsec is NORTH, positive Dec direction)
                        ra_deg = ref_ra_deg - delta_ra_arcsec / 3600.0
                        dec_deg = ref_dec_deg + delta_dec_arcsec / 3600.0
                        
                        # Convert to SkyCoord for HMS/DMS display
                        coord = SkyCoord(ra=ra_deg*u.deg, dec=dec_deg*u.deg, frame='icrs')
                        ra_hms = coord.ra.to_string(unit=u.hour, sep='hms', precision=2)
                        dec_dms = coord.dec.to_string(unit=u.degree, sep='dms', precision=2)
                        
                        print(f"           Offset: ΔRA={delta_ra_arcsec:+.2f}″, ΔDec={delta_dec_arcsec:+.2f}″")
                        print(f"           Absolute: {ra_hms} {dec_dms}")
                        print(f"           Decimal: RA={ra_deg:.6f}°, Dec={dec_deg:.6f}°")
                        
                        # Keep in decimal degrees format (string) for SkyCoord parsing
                        coord_str = f"{ra_deg} {dec_deg}"
                        coords.append(coord_str)
                        found = True
                        break
                    except (ValueError, IndexError):
                        continue
            
            if not found:
                print(f"    WARNING: Object {source_id} not found in source.dat")
                return None
        
        return coords if coords else None
    
    except Exception as e:
        print(f"    WARNING: Failed to read source.dat: {e}")
        return None


def read_image_dat_coordinates(image_dat_path, object_ids, id_mapping=None, mode="true"):
    """
    Read image plane coordinates from image.dat file.
    
    The image.dat file format contains absolute image plane coordinates with morphology info:
      object_id  ra_deg  dec_deg  semi_major  semi_minor  [other_columns...]
      
    For each object_id, there may be multiple entries (different morphologies/instances).
    Selection mode:
      - "true": Use the most circular one (smallest difference between semi_major and semi_minor)
      - "spherical_mean": Calculate spherical mean of all positions for each object ID
    
    Example image.dat content:
      1A  178.3290  7.9325  0.155  0.028  ...
      1A  178.3314  7.9363  0.092  0.038  ...
      1A  178.3352  7.9335  0.050  0.050  ...   <- Most circular
      2A  178.3253  7.9303  0.177  0.011  ...
    
    Args:
        image_dat_path: Path to image.dat file (e.g., output/poten/selected_output/sample_00027_z1.524_image.dat)
        object_ids: List of object IDs to extract (e.g., ["A1", "A2", "A3"])
        id_mapping: Dict mapping our object IDs to image.dat object IDs
                   (e.g., {"A1": "1A", "A2": "2A", "A3": "1C"})
        mode: Selection mode - "true" (most circular) or "spherical_mean" (mean of all)
        
    Returns:
        Dict mapping our object IDs to coordinate strings in "RA_deg Dec_deg" format, or None if not found
    """
    if id_mapping is None:
        id_mapping = {oid: oid for oid in object_ids}
    
    try:
        coords_dict = {}
        with open(image_dat_path, 'r') as f:
            lines = f.readlines()
        
        # Parse image.dat file and group by object ID
        # Format: object_id  ra_deg  dec_deg  semi_major  semi_minor  [other_columns...]
        entries_by_id = {}
        for line in lines:
            parts = line.strip().split()
            if not parts or parts[0].startswith('#'):
                continue
            try:
                obj_id = parts[0]
                ra_deg = float(parts[1])
                dec_deg = float(parts[2])
                semi_major = float(parts[3])
                semi_minor = float(parts[4])
                
                if obj_id not in entries_by_id:
                    entries_by_id[obj_id] = []
                entries_by_id[obj_id].append({
                    'ra': ra_deg,
                    'dec': dec_deg,
                    'semi_major': semi_major,
                    'semi_minor': semi_minor,
                    'circularity': abs(semi_major - semi_minor),  # Lower = more circular
                    'line': line.strip()
                })
            except (ValueError, IndexError):
                continue
        
        # For each requested object, find coordinates based on mode
        for obj_id in object_ids:
            image_id = id_mapping.get(obj_id, obj_id)
            
            if image_id not in entries_by_id:
                print(f"    WARNING: Object {image_id} not found in image.dat")
                return None
            
            if mode == "true":
                # Find most circular (smallest difference between axes)
                best_entry = min(entries_by_id[image_id], key=lambda x: x['circularity'])
                
                ra_deg = best_entry['ra']
                dec_deg = best_entry['dec']
                semi_major = best_entry['semi_major']
                semi_minor = best_entry['semi_minor']
                circularity = best_entry['circularity']
                
                # Print the image.dat line for this object
                print(f"      {obj_id:2s} ({image_id:3s}): {best_entry['line']}")
                print(f"           Semi-major={semi_major:.6f}, Semi-minor={semi_minor:.6f}, Δ={circularity:.6f}")
                
            elif mode == "spherical_mean":
                # Calculate spherical mean of all positions
                entries = entries_by_id[image_id]
                
                # Convert to SkyCoord array for spherical mean
                ras = [e['ra'] for e in entries]
                decs = [e['dec'] for e in entries]
                coords_array = SkyCoord(ra=ras*u.deg, dec=decs*u.deg, frame='icrs')
                
                # Calculate spherical mean in Cartesian coordinates
                cartesian_coords = coords_array.cartesian
                mean_x = cartesian_coords.x.mean()
                mean_y = cartesian_coords.y.mean()
                mean_z = cartesian_coords.z.mean()
                
                # Normalize the mean vector and convert back to spherical
                magnitude = np.sqrt(mean_x**2 + mean_y**2 + mean_z**2)
                mean_x_norm = mean_x / magnitude
                mean_y_norm = mean_y / magnitude
                mean_z_norm = mean_z / magnitude
                
                # Create a SkyCoord from the normalized Cartesian coordinates
                from astropy.coordinates import CartesianRepresentation
                mean_cartesian = CartesianRepresentation(mean_x_norm, mean_y_norm, mean_z_norm)
                mean_coord = SkyCoord(mean_cartesian, frame='icrs')
                ra_deg = mean_coord.ra.deg
                dec_deg = mean_coord.dec.deg
                
                entries_str = ', '.join([f"({e['ra']:.7f}, {e['dec']:.7f})" for e in entries])
                print(f"      {obj_id:2s} ({image_id:3s}): Spherical mean of {len(entries)} entries")
                print(f"           Entries: {entries_str}")
            else:
                raise ValueError(f"Unknown mode: {mode}. Use 'true' or 'spherical_mean'")
            
            # Convert to SkyCoord for HMS/DMS display
            coord = SkyCoord(ra=ra_deg*u.deg, dec=dec_deg*u.deg, frame='icrs')
            ra_hms = coord.ra.to_string(unit=u.hour, sep='hms', precision=2)
            dec_dms = coord.dec.to_string(unit=u.degree, sep='dms', precision=2)
            
            print(f"           Decimal: RA={ra_deg:.6f}°, Dec={dec_deg:.6f}°")
            print(f"           HMS/DMS: {ra_hms} {dec_dms}")
            
            # Keep in decimal degrees format (string) for SkyCoord parsing
            coord_str = f"{ra_deg} {dec_deg}"
            coords_dict[obj_id] = coord_str
        
        return coords_dict if coords_dict else None
    
    except Exception as e:
        print(f"    WARNING: Failed to read image.dat: {e}")
        return None


def spherical_mean_icrs(coord_strings, object_ids=None):
    """
    Calculate spherical mean of ICRS coordinates.
    
    When multiple source images (e.g., 1A, 1B, 1C) are detected, their positions
    are not simply averaged in Cartesian coordinates. Instead, they are converted
    to 3D unit vectors on the celestial sphere, averaged, and converted back to
    spherical coordinates. This preserves the spherical geometry.
    
    Algorithm:
      1. Parse coordinate strings (supports decimal degrees "RA Dec" or HMS/DMS formats)
      2. Convert RA, Dec to 3D Cartesian unit vectors on the celestial sphere
      3. Average the vectors: x_mean = mean(x), y_mean = mean(y), z_mean = mean(z)
      4. Renormalize: norm = sqrt(x_mean² + y_mean² + z_mean²)
      5. Convert back to RA, Dec using atan2 and arcsin
    
    Args:
        coord_strings: list of coordinate strings in any supported format:
                      - Decimal degrees: "178.3284 7.9321"
                      - HMS/DMS: "11h53m19.8s +07d55m56.4s"
        object_ids: optional list of object IDs (e.g., ["A1", "A2", "A3"]) for debug output
        
    Returns:
        SkyCoord object with the spherical mean position in ICRS frame
        
    Example:
        >>> coords = ["178.3284 7.9321", "178.3292 7.9298", "178.3301 7.9284"]
        >>> mean_coord = spherical_mean_icrs(coords, ["A1", "A2", "A3"])
        >>> print(mean_coord.to_string('hmsdms'))
        11h53m19.78s +07d55m56.34s
    """
    coords = []
    parsed_coords = []
    for i, c in enumerate(coord_strings):
        # Try to parse as decimal degrees first (space-separated "RA Dec")
        try:
            parts = c.split()
            if len(parts) == 2:
                ra_deg = float(parts[0])
                dec_deg = float(parts[1])
                coord = SkyCoord(ra=ra_deg*u.deg, dec=dec_deg*u.deg, frame='icrs')
                coords.append(coord)
                parsed_coords.append((object_ids[i] if object_ids else f"Input {i}", coord))
            else:
                # Fall back to parse_coordinate_string for HMS/DMS format
                coord = parse_coordinate_string(c)
                coords.append(coord)
                parsed_coords.append((object_ids[i] if object_ids else f"Input {i}", coord))
        except (ValueError, IndexError):
            # Fall back to parse_coordinate_string for HMS/DMS format
            coord = parse_coordinate_string(c)
            coords.append(coord)
            parsed_coords.append((object_ids[i] if object_ids else f"Input {i}", coord))
    
    # Print input coordinates
    print("      Inputs to spherical mean:")
    for label, coord in parsed_coords:
        ra_hms = coord.ra.to_string(unit=u.hour, sep='hms', precision=2)
        dec_dms = coord.dec.to_string(unit=u.degree, sep='dms', precision=2)
        ra_deg = coord.ra.deg
        dec_deg = coord.dec.deg
        print(f"        {label:3s}: {ra_hms} {dec_dms} = RA {ra_deg:.6f}°, Dec {dec_deg:.6f}°")
    
    ra = np.array([c.ra.to(u.rad).value for c in coords])
    dec = np.array([c.dec.to(u.rad).value for c in coords])
    
    # Convert to 3D unit vectors
    x = np.cos(dec) * np.cos(ra)
    y = np.cos(dec) * np.sin(ra)
    z = np.sin(dec)
    
    # Average vector, then renormalize
    x_m, y_m, z_m = np.mean(x), np.mean(y), np.mean(z)
    norm = np.sqrt(x_m**2 + y_m**2 + z_m**2)
    x_m, y_m, z_m = x_m/norm, y_m/norm, z_m/norm
    
    # Back to RA/Dec
    ra_m = np.arctan2(y_m, x_m) * u.rad
    dec_m = np.arcsin(z_m) * u.rad
    result = SkyCoord(ra=ra_m.to(u.deg), dec=dec_m.to(u.deg), frame="icrs")
    
    # Print result
    ra_hms = result.ra.to_string(unit=u.hour, sep='hms', precision=2)
    dec_dms = result.dec.to_string(unit=u.degree, sep='dms', precision=2)
    print(f"      Spherical mean: {ra_hms} {dec_dms} = RA {result.ra.deg:.6f}°, Dec {result.dec.deg:.6f}°")
    
    return result


def extract_timedelays(poten_fits_path, config, output_dir, leading_image_name=None):
    """
    Extract time delay surface from a potential FITS file.
    
    Supports both static and per-sample source plane coordinates:
    
    STATIC COORDINATES:
      Set config["source_plane_coords"] to a string like "11h53m19.6s +07d55m57s"
      This fixed position is used for all samples (less accurate).
    
    PER-SAMPLE COORDINATES (recommended):
      Set config["source_plane_coords"] = "infer_from_source.dat"
      This reads unique source positions from lenstool's source.dat output files.
      
      Required config entries for per-sample mode:
        - "source_dat_directory": Directory path (e.g., "output/poten/selected_output")
        - "source_dat_object_id_mapping": Dict mapping image IDs to source.dat IDs
                                         (e.g., {"A1": "1A", "A2": "1B", "A3": "1C"})
        - "source_plane_coords_default": Fallback position if source.dat unavailable
      
      The code automatically:
        1. Extracts sample name from FITS filename (e.g., "sample_00027_z1.524")
        2. Looks for sample_input/sample_00027_z1.524.par for reference coordinates
        3. Reads source.dat offsets from source_dat_directory/sample_00027_z1.524_source.dat
        4. Converts arcsecond offsets to absolute coordinates
        5. Computes spherical mean of multiple source positions
        6. Uses this position for time delay calculation
    
    Args:
        poten_fits_path: Path to the potential FITS file (sample_<X>_z<z_source>_poten.fits)
        config: Configuration dictionary with:
                - cosmology: {z_lens, z_source, D_l_Mpc, D_s_Mpc, D_ls_Mpc}
                - image_locations: {A1: "11h53m...", A2: "...", A3: "..."}
                  OR "infer_from_image.dat" to read from image.dat files
                - source_plane_coords: coordinate string or "infer_from_source.dat"
                - source_dat_directory: path to source.dat files (if inferring)
                - source_dat_object_id_mapping: {our_id: source.dat_id}
        output_dir: Directory to save output FITS files
    """
    
    # Create output directory if needed
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Load config parameters
    z_lens = config['cosmology']['z_lens']
    z_source = config['cosmology']['z_source']
    D_l_Mpc = config['cosmology']['D_l_Mpc']
    D_s_Mpc = config['cosmology']['D_s_Mpc']
    D_ls_Mpc = config['cosmology']['D_ls_Mpc']
    
    # Get image locations for reference (leading image)
    image_locations = config.get('image_locations', {})
    
    # Check if we should infer image locations from image.dat
    if image_locations == "infer_from_image.dat":
        # Get image.dat directory from config (default to selected_output)
        image_dat_dir = config.get('image_dat_directory', 'output/poten/selected_output')
        
        # Extract sample name from FITS file (without _poten suffix)
        poten_filename = Path(poten_fits_path).stem  # Remove .fits extension
        # Remove _poten suffix if present, but it should already be gone
        sample_name = poten_filename.replace('_poten', '')
        
        # Construct path to image.dat file matching the sample name
        image_dat_path = Path(image_dat_dir) / f"{sample_name}_image.dat"

        # Get ID mapping from config
        image_object_ids = config.get('image_object_ids')
        id_mapping = config.get('image_dat_object_id_mapping')
        image_dat_mode = config.get('image_dat_mode')
        
        print(f"    Reading image coordinates from: {image_dat_path.name}")
        image_coords_dict = read_image_dat_coordinates(str(image_dat_path), image_object_ids, id_mapping, mode=image_dat_mode)
        
        if image_coords_dict is None:
            print(f"    ERROR: Could not read image.dat")
            return None
        else:
            # Convert dict to image_locations format expected by rest of code
            image_locations = image_coords_dict
    
    image_names = list(image_locations.keys())
    if not image_names:
        print("    ERROR: No image_locations in config")
        return None
    
    # Use the provided leading_image_name parameter (from config)
    # This parameter MUST have been validated in main() before calling this function
    if not leading_image_name:
        raise ValueError(f"ERROR: leading_image_name was not provided to extract_timedelays()")
    if leading_image_name not in image_locations:
        raise ValueError(f"ERROR: leading_image_name '{leading_image_name}' not in image_locations: {list(image_locations.keys())}")
    
    leading_image_coord = image_locations[leading_image_name]
    print(f"    Leading image: {leading_image_name} at {leading_image_coord}")
    
    # Get source plane coordinates
    beta_coords = config.get('source_plane_coords')
    
    # Check if we should infer from source.dat
    # Per-sample coordinate inference workflow:
    #   1. Check if config specifies "infer_from_source.dat" mode
    #   2. Extract sample identifier from FITS filename (e.g., "sample_00027_z1.524_poten")
    #   3. Read reference coordinates from sample_input/{sample_name}.par
    #   4. Read source.dat offsets from {source_dat_directory}/{sample_name}_source.dat
    #   5. Convert arcsecond offsets to absolute coordinates
    #   6. Compute spherical mean of multiple source positions (1A, 1B, 1C -> mean position)
    #   7. Use inferred position for this sample's time delay calculation
    #
    # PRE-CALCULATED COORDINATE OPTION:
    #   If beta_coords is a list with one element, it's a pre-calculated position
    #   If beta_coords is a list with multiple elements, compute spherical mean
    if beta_coords == "infer_from_source.dat":
        # Get source.dat directory from config (default to selected_output)
        source_dat_dir = config.get('source_dat_directory', 'output/poten/selected_output')
        
        # Extract sample name from poten_fits_path (e.g., "sample_00027_z1.524")
        poten_filename = Path(poten_fits_path).stem  # Remove .fits extension
        # Remove _poten suffix if present (handles both old and new naming conventions)
        sample_name = poten_filename.replace('_poten', '')
        
        # Construct path to source.dat file matching the sample name
        source_dat_path = Path(source_dat_dir) / f"{sample_name}_source.dat"
        
        # Construct path to PAR file (e.g., "sample_00027_z1.524.par") in sample_input directory
        par_filename = f"{sample_name}.par"
        par_path = Path('sample_input') / par_filename
        
        # Get ID mapping from config
        id_mapping = config.get('source_dat_object_id_mapping', {oid: oid for oid in image_names})
        
        print(f"    Reading source coordinates from: {source_dat_path.name}")
        beta_coords = read_source_dat_coordinates(str(source_dat_path), str(par_path), image_names, id_mapping)
        
        if beta_coords is None:
            print(f"    ERROR: Could not read source.dat")
            return None
    
    # Compute spherical mean from coordinates
    def compute_mean_coord(coords_list):
        """Compute mean of SkyCoord objects, or return single if only one."""
        if len(coords_list) > 1:
            ra_mean = np.mean([c.ra.deg for c in coords_list])
            dec_mean = np.mean([c.dec.deg for c in coords_list])
            return SkyCoord(ra=ra_mean, dec=dec_mean, unit='deg', frame='icrs')
        return coords_list[0]
    
    if isinstance(beta_coords, str):
        # Direct coordinate string from config (HMS/DMS or decimal string)
        beta_icrs = parse_coordinate_string(beta_coords)
    elif isinstance(beta_coords, (list, tuple)) and len(beta_coords) > 0:
        if isinstance(beta_coords[0], str):
            # Multiple HMS/DMS strings from source.dat
            beta_icrs = spherical_mean_icrs(beta_coords, image_names)
        elif isinstance(beta_coords[0], (list, tuple)):
            # Coordinate pairs - check if relative offsets or absolute
            reference_coord = config.get('reference_coord', None)
            is_relative = reference_coord and all(abs(pair[0]) < 100 and abs(pair[1]) < 100 for pair in beta_coords)
            
            if is_relative:
                # Convert arcsecond offsets to absolute coordinates
                print(f"    Converting relative arcsecond offsets to absolute coordinates...")
                print(f"    Reference coordinate: RA={reference_coord[0]:.6f}°, Dec={reference_coord[1]:.6f}°")
                coords = []
                for i, (delta_ra_arcsec, delta_dec_arcsec) in enumerate(beta_coords):
                    ra_deg = reference_coord[0] - (delta_ra_arcsec / 3600.0)
                    dec_deg = reference_coord[1] + (delta_dec_arcsec / 3600.0)
                    coords.append(SkyCoord(ra=ra_deg, dec=dec_deg, unit='deg', frame='icrs'))
                    print(f"      Source {i+1}: delta_RA={delta_ra_arcsec:.4f}\", delta_Dec={delta_dec_arcsec:.4f}\" -> RA={ra_deg:.6f}°, Dec={dec_deg:.6f}°")
            else:
                # Treat as absolute [ra_deg, dec_deg] pairs
                coords = [SkyCoord(ra=pair[0], dec=pair[1], unit='deg', frame='icrs') for pair in beta_coords]
            
            beta_icrs = compute_mean_coord(coords)
            if len(coords) > 1:
                print(f"    Spherical mean: RA={beta_icrs.ra.deg:.6f}°, Dec={beta_icrs.dec.deg:.6f}°")
        elif isinstance(beta_coords[0], (int, float)):
            # Single [ra_deg, dec_deg] pair
            beta_icrs = SkyCoord(ra=beta_coords[0], dec=beta_coords[1], unit='deg', frame='icrs')
        else:
            print("    ERROR: Could not determine source plane coordinates")
            return None
    else:
        print("    ERROR: Could not determine source plane coordinates")
        return None
    
    print(f"  Source plane (beta): {beta_icrs.to_string('hmsdms')}")
    print(f"  Source plane (degrees): RA={beta_icrs.ra.deg:.6f}°, Dec={beta_icrs.dec.deg:.6f}°")
    
    # Print image plane coordinates for DS9 verification
    print(f"\n  IMAGE PLANE COORDINATES (for DS9 verification):")
    for img_name, img_coord in image_locations.items():
        if isinstance(img_coord, (list, tuple)):
            # Already in [ra_deg, dec_deg] format
            print(f"    {img_name}: RA={img_coord[0]:.6f}°, Dec={img_coord[1]:.6f}°")
        else:
            # Parse string format
            try:
                coord = parse_coordinate_string(img_coord)
                print(f"    {img_name}: RA={coord.ra.deg:.6f}°, Dec={coord.dec.deg:.6f}° (from string: {img_coord})")
            except:
                print(f"    {img_name}: {img_coord} (could not parse)")
    
    # Load potential FITS file (data)
    with fits.open(poten_fits_path) as hdul:
        # Primary HDU contains the potential data
        psi_arcsec2 = hdul[0].data.astype(np.float64)
        poten_header = hdul[0].header
    
    # Get potential map dimensions
    ny, nx = psi_arcsec2.shape
    print(f"    Potential map dimensions: {nx} × {ny}")
    
    # ---- WCS + linear mapping from pixel (x,y) -> (East, North) angles
    base_hdr = fits.getheader(poten_fits_path).copy()
    w = WCS(base_hdr).celestial
    if w.wcs.has_cd():
        CD = w.wcs.cd[:2, :2]  # deg/pix
    else:
        PC = w.wcs.get_pc()[:2, :2]
        CDELT = np.array(w.wcs.cdelt[:2])
        CD = PC @ np.diag(CDELT)  # deg/pix

    yy, xx = np.mgrid[0:ny, 0:nx]
    deg2rad = np.pi / 180.0
    arcsec_to_rad = u.arcsec.to(u.rad)

    # θ field (E/N radians) at every pixel (tangent-plane small-angle with the same origin)
    dE_deg = CD[0,0]*xx + CD[0,1]*yy
    dN_deg = CD[1,0]*xx + CD[1,1]*yy
    theta_E = dE_deg * deg2rad
    theta_N = dN_deg * deg2rad

    # beta_icrs = SkyCoord(beta_str, frame="icrs")
    xb, yb = w.all_world2pix(beta_icrs.ra.deg, beta_icrs.dec.deg, 0)  # 0-based pixel location for beta
    # Convert that absolute sky coord into the same tangent-plane basis used for theta_E/theta_N
    beta_E = (CD[0,0]*xb + CD[0,1]*yb) * deg2rad
    beta_N = (CD[1,0]*xb + CD[1,1]*yb) * deg2rad

    # if verbose:
    #     print(f"[FIXED beta] ICRS = {beta_icrs.to_string('hmsdms')}")
    #     print(f"[FIXED beta] pixel ~ ({xb:.2f},{yb:.2f})")
    #     print(f"[FIXED beta] (E,N) = [{beta_E/arcsec_to_rad:.3f}, {beta_N/arcsec_to_rad:.3f}] arcsec")

    # ---- Geometric term with FIXED beta: 0.5 * |theta - beta|^2
    dE = theta_E - beta_E
    dN = theta_N - beta_N
    geom = 0.5 * (dE*dE + dN*dN)  # radians^2

    # ---- Convert psi from arcsec^2 to rad^2 and build Fermat potential
    psi_rad2 = psi_arcsec2 * (arcsec_to_rad**2)
    fermat = geom - psi_rad2  # radians^2

    # ---- Coefficient to seconds
    D_factor = (D_l_Mpc * D_s_Mpc / D_ls_Mpc) * u.Mpc
    z_l = z_lens
    coeff_s = ((1.0 + z_l) * (D_factor / c)).to(u.s).value

    tau_sec  = (coeff_s * fermat).astype(np.float32)
    tau_days = (tau_sec / 86400.0).astype(np.float32)
    
    print(f"    Time delay range: {np.nanmin(tau_days):.4f} to {np.nanmax(tau_days):.4f} days")
    
    # Create output FITS file
    output_filename = Path(poten_fits_path).name
    # Handle both old (_poten.fits) and new (.fits) naming conventions
    if '_poten.fits' in output_filename:
        output_filename = output_filename.replace('_poten.fits', '_timedelay.fits')
    else:
        output_filename = output_filename.replace('.fits', '_timedelay.fits')
    output_path = output_dir / output_filename
    
    # PRIMARY HDU: time delays in seconds
    hdr_primary = fits.Header()
    hdr_primary.update(WCS(poten_header).to_header(relax=True))
    hdr_primary["BUNIT"] = "s"
    hdr_primary["Z_LENS"] = z_lens
    hdr_primary["Z_SOURCE"] = z_source
    hdr_primary["D_L_MPC"] = D_l_Mpc
    hdr_primary["D_S_MPC"] = D_s_Mpc
    hdr_primary["D_LS_MPC"] = D_ls_Mpc
    hdu0 = fits.PrimaryHDU(tau_sec, header=hdr_primary)
    
    # EXT1: absolute days
    hdr1 = fits.Header()
    hdr1.update(WCS(poten_header).to_header(relax=True))
    hdr1["BUNIT"] = "d"
    hdu1 = fits.ImageHDU(tau_days, header=hdr1, name="DAYS")
    
    # EXT2: days relative to the leading image
    # If leading_image_name is specified (from best-fit model), use that image's time delay as reference
    # Otherwise, use the minimum time delay among image positions in this sample
    image_tau_values = {}
    for img_name, img_coord in image_locations.items():
        try:
            # Handle both string (HMS/DMS format) and list [ra_deg, dec_deg] formats
            if isinstance(img_coord, (list, tuple)):
                coord = SkyCoord(ra=img_coord[0], dec=img_coord[1], unit='deg', frame='icrs')
            else:
                coord = parse_coordinate_string(img_coord)
            xi, yi = w.all_world2pix(coord.ra.deg, coord.dec.deg, 0)
            xi_int, yi_int = int(np.rint(xi)), int(np.rint(yi))
            if 0 <= xi_int < nx and 0 <= yi_int < ny:
                tau_at_img = float(tau_days[yi_int, xi_int])
                image_tau_values[img_name] = tau_at_img
                print(f"      {img_name} (RA={coord.ra.deg:.6f}, Dec={coord.dec.deg:.6f}): τ = {tau_at_img:.2f} days")
            else:
                print(f"      {img_name}: pixel ({xi_int}, {yi_int}) out of bounds")
        except Exception as e:
            print(f"      {img_name}: Error reading coordinate - {e}")
    
    # Determine reference image and its time delay - EXPLICIT, NO FALLBACKS
    if not leading_image_name:
        raise ValueError(f"ERROR: leading_image_name must be specified in config. Got: {leading_image_name}")
    
    if leading_image_name not in image_tau_values:
        raise ValueError(f"ERROR: Leading image '{leading_image_name}' not found in image_tau_values: {list(image_tau_values.keys())}")
    
    # Use the specified leading image from config
    ref_days = image_tau_values[leading_image_name]
    leading_img = leading_image_name
    print(f"    Using leading image '{leading_img}' from config with time delay {ref_days:.2f} days")
    
    days_rel = (tau_days - ref_days).astype(np.float32)
    
    hdr2 = fits.Header()
    hdr2.update(WCS(poten_header).to_header(relax=True))
    hdr2["BUNIT"] = "d"
    hdr2["COMMENT"] = "Time delays relative to the leading image (minimum at image positions)"
    hdu2 = fits.ImageHDU(days_rel, header=hdr2, name="DAYS_REL")
    
    # EXT3: geometric term (for reference)
    hdr3 = fits.Header()
    hdr3.update(WCS(poten_header).to_header(relax=True))
    hdr3["BUNIT"] = "rad2"
    hdu3 = fits.ImageHDU(geom.astype(np.float32), header=hdr3, name="GEOM")
    
    # Write FITS file
    hdul_out = fits.HDUList([hdu0, hdu1, hdu2, hdu3])
    hdul_out.writeto(output_path, overwrite=True)
    
    return str(output_path)






def main():
    """Main entry point for time delay extraction."""
    parser = argparse.ArgumentParser(
        description="Extract time delay surfaces from potential FITS files"
    )
    parser.add_argument(
        'poten_dir',
        help='Directory containing potential FITS files'
    )
    parser.add_argument(
        'config_file',
        help='Configuration file (timedelay_config.json)'
    )
    parser.add_argument(
        '-output',
        default='samples/output/timedelay',
        help='Output directory for time delay FITS files (default: samples/output/timedelay)'
    )
    parser.add_argument(
        '-z',
        type=float,
        default=None,
        help='Source redshift filter (only process files with this redshift in name)'
    )
    
    args = parser.parse_args()
    
    # Load configuration
    config = load_config(args.config_file)
    
    # Get list of potential files (handles both old naming with _poten and new naming without)
    poten_dir = Path(args.poten_dir)
    poten_files = sorted(poten_dir.glob('sample_*_z*.fits'))
    # Filter out any files that don't look like potential files
    poten_files = [f for f in poten_files if '_z' in f.name]
    
    if args.z is not None:
        # Filter by redshift in filename
        z_str = f'_z{args.z:.3f}'
        poten_files = [f for f in poten_files if z_str in f.name]
    
    if not poten_files:
        print(f"No potential FITS files found in {poten_dir}")
        return
    
    print(f"Found {len(poten_files)} potential FITS files")
    
    # Identify leading image from config - MUST BE SPECIFIED
    print(f"\n{'='*70}")
    print(f"STEP 1: Check leading image configuration")
    print(f"{'='*70}")
    leading_image_name = config.get('leading_image_name')
    if not leading_image_name:
        raise ValueError(f"ERROR: 'leading_image_name' MUST be specified in config file. Cannot proceed without explicit leading image.")
    print(f"  ✓ Leading image from config: {leading_image_name}")
    
    # Process each file
    print(f"\n{'='*70}")
    print(f"STEP 2: Extract time delays for all samples")
    print(f"{'='*70}")
    processed = 0
    for i, poten_path in enumerate(poten_files, 1):
        print(f"\n[{i}/{len(poten_files)}] {poten_path.name}")
        
        result = extract_timedelays(poten_path, config, args.output, leading_image_name=leading_image_name)
        if result:
            print(f"  ✓ Saved to: {result}")
            processed += 1
    
    print(f"\n✓ Successfully processed {processed}/{len(poten_files)} files")
    print(f"✓ Time delay FITS files saved to: {args.output}")
    
    # Read and display leading image info from best-fit file if it exists
    output_dir = Path(args.output)
    # Filter to only the best_fit file for this specific redshift
    redshift_filter = f"z{args.z}" if args.z else None
    best_fit_files = sorted(output_dir.glob('sample_best_*.fits'), reverse=True)
    best_fit_files = [f for f in best_fit_files if redshift_filter is None or redshift_filter in f.name]
    if best_fit_files:
        best_fit_path = best_fit_files[0]
        print(f"\n{'='*70}")
        print(f"STEP 3: Confirm leading image from output FITS files")
        print(f"{'='*70}")
        try:
            with fits.open(best_fit_path) as hdul:
                refdays = hdul[2].header.get('REFDAYS', None)
                z_source = hdul[0].header.get('Z_SOURCE', None)
                days_rel_data = hdul[2].data  # DAYS_REL HDU
                w = WCS(hdul[2].header).celestial
                
                image_locations = config.get('image_locations', {})
                if image_locations == "infer_from_image.dat":
                    image_dat_dir = config.get('image_dat_directory', 'output/poten/selected_output')
                    poten_filename = best_fit_path.name.replace('_timedelay.fits', '')
                    image_dat_path = Path(image_dat_dir) / f"{poten_filename}_image.dat"
                    image_object_ids = config.get('image_object_ids', ['2A', '2B', '2C'])
                    id_mapping = config.get('image_dat_object_id_mapping', {oid: oid for oid in image_object_ids})
                    image_dat_mode = config.get('image_dat_mode', 'true')
                    image_locations_dict = read_image_dat_coordinates(str(image_dat_path), image_object_ids, id_mapping, mode=image_dat_mode)
                    if image_locations_dict:
                        image_locations = image_locations_dict
                
                leading_image = None
                min_days_rel = float('inf')
                
                for img_name, img_coord in image_locations.items():
                    try:
                        # Handle both string (HMS/DMS format) and list [ra_deg, dec_deg] formats
                        if isinstance(img_coord, (list, tuple)):
                            coord = SkyCoord(ra=img_coord[0], dec=img_coord[1], unit='deg', frame='icrs')
                        else:
                            coord = parse_coordinate_string(img_coord)
                        xi, yi = w.all_world2pix(coord.ra.deg, coord.dec.deg, 0)
                        xi_int, yi_int = int(np.rint(xi)), int(np.rint(yi))
                        ny, nx = days_rel_data.shape
                        if 0 <= xi_int < nx and 0 <= yi_int < ny:
                            days_rel_val = float(days_rel_data[yi_int, xi_int])
                            if days_rel_val < min_days_rel:
                                min_days_rel = days_rel_val
                                leading_image = img_name
                    except:
                        pass
                
                if leading_image is not None:
                    print(f"File: {best_fit_path.name}")
                    print(f"Redshift: z_source = {z_source}")
                    print(f"\n>>> LEADING IMAGE: {leading_image} <<<")
                    print(f"    Reference time delay (REFDAYS): {refdays:.2f} days")
                    print(f"    This is the image with the most negative absolute time delay")
                    print(f"    (and DAYS_REL ≈ 0.0 at this location)")
                    print(f"{'='*70}")
        except Exception as e:
            pass


if __name__ == '__main__':
    main()
